# Generated by Django 6.0.1 on 2026-07-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_outgoing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
